server:
  host: '::'
  port: 3444
  # trust-proxy: 127.0.0.1, ::1

# folder to store certificates, database in
state: '/var/lib/acme-distributor'

providers:
  le-cf:
    type: acme-sh
    # custom options per plugin
    dns: dns_cf
    env:
      CF_Key: 1234
      CF_Email: you@example.com
  ca:
    type: ca
    key: path/to/ca.key
    cert: path/to/ca.cert

certificates:
  # "names" means get and renew a cert with those names
  company.com:
    names:
    - company.com
    - '*.company.com'
    provider: le-cf
  # "domains" option means "issue certificates for this domain and it's subdomains with this provider"
  # certificates per subdomain will be issued automatically, as non-wildcard.
  # adding a *. to domains means that a certificate for x.y.domain.tld should be issued with this provider
  # internal, *.internal: issue certificates for any domain under .internal and it's subdomains
  # **.internal, don't limit subs, so one can do x.y.z.internal, without any extras
  thing.internal:
    domains:
    - thing.internal
    - '*.thing.internal'
    provider: ca

tokens:
  - hashed: 'sha5hex(token)'
    # insecure, but also possible:
    # plain: 'token'
    allowFrom: # optional access restriction
      - 1.2.3.4/24
      - efef::efef::/64
      - 4.3.2.1 # or 4.3.2.1/32
    restrictNames: # optional restrict names to the ones in the list
      - '*.internal'
